import "@/styles/reset.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.scss";

const inter = Roboto({ weight: "400", style: "normal", subsets:['latin'] });

export const metadata: Metadata = {
  title: "Cleaning company Notos Oy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
